### ISSUE TITLE
Pony /tg/ Round Start/End Sounds

### ISSUE THREAD

**Issue by Poopsikins** [Poopsikins/mlpstation13#7]
I redid the /tg/ station round end sounds with the magic of 15.ai because I like them so much.
https://u.smutty.horse/mcfhglshxtu.rar

I'm not sure how you can add these to the Round Start/End but If anyone can look into it that'll be great!

**Comment by vultraz168** [comment]
#10

**Comment by Poopsikins** [comment]
Thanks!
